version: 2
jobs:
  test:
    docker:
      - image: node:10.15.3-alpine
    steps:
      - checkout
      - run:
          name: Install
          command: npm i
      - run:
          name: Lint
          command: npx eslint index.js ./lib/**
      - run:
          name: Unit Tests
          command: npm test
  coverage:
    docker:
      - image: node:10.15.3-alpine
    steps:
      - checkout
      - run:
          name: Install
          command: npm i
      - run:
          name: Coverage
          command: |
            npm run coverage
            npx nyc report --reporter=text-lcov | npx coveralls

workflows:
  version: 2
  test:
    jobs:
      - test
  release:
    jobs:
      - test
      - coverage:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/




