version: 2
jobs:
  build:
    docker:
      - image: node:10.15.3-alpine
    steps:
      - checkout
      - run:
          name: install
          command: npm i
      - run:
          name: coverage
          command: |
            npm run coverage
            npx nyc report --reporter=text-lcov | npx coveralls
